project="idptno-afterrole"
Site="testing"
quota_pods="5"
quota_cpu_request="5"
quota_memory_request="5Gi"
quota_cpu_limit="10"
quota_memory_limit="10Gi"
quota_storage="10"
#GroupDL="CN=Tech-Infrastructure Architecture-Design & Planning,OU=DL,DC=internal,DC=eg,DC=vodafone,DC=com"
EgressIP="192.1.1.1"
#LABEL="APP=WORK"
