
project                =   "idptest"
Site		       =   "Testing"
quota_pods             =   "5"
quota_cpu_request      =   "5"
quota_memory_request   =   "5Gi"
quota_cpu_limit        =   "10"
quota_memory_limit     =   "10Gi"
quota_storage          =   "10"
#GroupDL		       =   "Group3"
EgressIP               =   ""
EgressIpHA               =   ""
#NT			= ("Thon" "wael" "Hend")
#LABEL			= "VFlabel"
#DuplicateCheckBox 	= "False"
